package com.aspsine.bluechat.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table NOTICE.
 */
public class Notice {

    private Long id;
    private java.util.Date time;
    private Integer type;
    private String message;

    // KEEP FIELDS - put your custom fields here

    /**
     * 接受到的消息
     */
    public static final int TYPE_IN_COMING = 0;
    /**
     * 发�?�的消息
     */
    public static final int TYPE_RETURNING = 1;

    /**
     * 新闻
     */
    public static final int TYPE_NEWS = 2;

    /**
     * 系统消息
     */
    public static final int TYPE_SYSTEM = 3;

    /**
     * 时间
     */
    public static final int TYPE_TIME = 4;
    // KEEP FIELDS END

    public Notice() {
    }

    public Notice(Long id) {
        this.id = id;
    }

    public Notice(Long id, java.util.Date time, Integer type, String message) {
        this.id = id;
        this.time = time;
        this.type = type;
        this.message = message;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return super.toString();
    }
    // KEEP METHODS END

}
